spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/arka_db
    username: postgres
    password: "123"
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/arka_db 
    username: postgres
    password: 123
    pool:
      initial-size: 5
      max-size: 20
      
logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG  # Ver queries SQL ejecutadas
    io.r2dbc.postgresql.PARAM: DEBUG  # Ver par√°metros de las queries
    com.tuempresa.cart: DEBUG     

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    eureka-server-connect-timeout-seconds: 10
  instance:
    hostname: localhost
    prefer-ip-address: true